### ISSUE TITLE
HTML Scanner

### ISSUE THREAD

**Issue by mikeloomans** [basst85/coronacheck-web-scanner#1]
Hoi Bastiaan,

Wat jij bent aan het maken, daar ben ik precies naar op zoek. Dit om de coronapas check-in te automatiseren. Ik heb je script gedownload maar hij opent geen camera app op de mobiele devices, klopt dat?

**Comment by basst85** [comment]
@mikeloomans Klopt, hij werkt niet lekker op mobiele devices. Maar daar heb je ook de officiële CoronaCheck app voor 😉

Let trouwens op: 
Het is momenteel wettelijk niet toegestaan om bij toegang de controle uit te voeren met iets anders dan de officiële CoronaCheck Scanner app: https://wetten.overheid.nl/BWBR0024705/2021-06-24/#HoofdstukVa_Paragraaf3a_Artikel58re
